[data]
min_phase = -10
max_phase = 40
train_frac = 0.75
seed = 12345
cosmological_model = "WMAP7"
salt_model = "salt2"
data_dir = "../../../../data"
idr = "IDR_eTmax.txt"
mask = "mask_info_wmin_wmax.txt"
meta = "meta.csv"

[pae]
# === Required ===
# --- Data ---
validation_frac = 0.1
seed = 12345

# Base-case PAE model
[pae.model]
seed = 12345
backend = "tf"
name = "Default"
validation_frac = 0
save_best = false
batch_size = 57                                             # Only correct for the SNFactory data
val_every = 100
delta_av_epochs = 1000
zs_epochs = 1000
delta_m_epochs = 5000
delta_p_epochs = 5000
final_epochs = 5000
delta_av_lr = 0.005
zs_lr = 0.005
delta_m_lr = 0.005
delta_p_lr = 0.001
final_lr = 0.001
delta_av_lr_decay_steps = 300
zs_lr_decay_steps = 300
delta_m_lr_decay_steps = 300
delta_p_lr_decay_steps = 300
final_lr_decay_steps = 300
delta_av_lr_decay_rate = 0.95
zs_lr_decay_rate = 0.95
delta_m_lr_decay_rate = 0.95
delta_p_lr_decay_rate = 0.95
final_lr_decay_rate = 0.95
delta_av_lr_weight_decay_rate = 0.0001
zs_lr_weight_decay_rate = 0.0001
delta_m_lr_weight_decay_rate = 0.0001
delta_p_lr_weight_decay_rate = 0.0001
final_lr_weight_decay_rate = 0.0001
min_train_redshift = 0.02
min_test_redshift = 0.02
min_val_redshift = 0.02
max_train_redshift = 1.0
max_test_redshift = 1.0
max_val_redshift = 1.0
min_train_phase = -10
min_test_phase = -10
min_val_phase = -10
max_train_phase = 40
max_test_phase = 40
max_val_phase = 40
n_z_latents = 3
physical_latents = true
seperate_latent_training = true
seperate_z_latent_training = false
architecture = "dense"
encode_dims = [256, 128]
dropout = 0
batch_normalisation = false
activation = "relu"
loss = "WHuber"
optimiser = "AdamW"
scheduler = "ExponentialDecay"
colourlaw = "../../../../data/colourlaws/F99_colourlaw.txt"
kernel_regulariser = "L2"
kernel_regulariser_penalty = 100                              # Not used if kernel_regulariser is None
amplitude_offset_scale = 1.0
phase_offset_scale = -0.02
mask_fraction = 0.1
use_amplitude = true
loss_clip_delta = 25
loss_residual_penalty = 0
loss_delta_m_penalty = 0
loss_delta_av_penalty = 0
loss_delta_p_penalty = 0
loss_covariance_penalty = 50000                             # Seems excessive
loss_decorrelate_all = true
loss_decorrelate_dust = true
