name: suPAErnova
dependencies:
  - astropy
  - cairocffi
  - click
  - coloredlogs
  - matplotlib
  - pandas
  - pydantic
  - sncosmo
  - toml
  - tqdm
  - tensorflow-cpu>=2.18,<2.19
  - tf-keras>=2.18,<2.19
  - tensorflow-probability>=0.25
  - tensorboard>=2.18,<2.19
  - pip
  - pip:
    - -e .
    - chainconsumer
    - tensorboard_plugin_profile>2.20
