name: suPAErnova
dependencies:
  - astropy
  - cairocffi
  - chainconsumer
  - click
  - coloredlogs
  - matplotlib
  - pandas
  - pydantic
  - sncosmo
  - toml
  - tqdm
  - tensorflow-cpu>=2.18,<2.19
  - tf-keras>=2.18,<2.19
  - tensorflow-probability>=0.25
  - tensorboard>=2.18,<2.19
  - tensorboard_plugin_profile>2.20
