[project]
name = "suPAErnova"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Patrick Armstrong", email = "patrick.james.1998@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "astropy>=7.0.1",
    "click>=8.1.8",
    "coloredlogs>=15.0.1",
    "matplotlib>=3.10.0",
    "pandas>=2.2.3",
    "sncosmo>=2.12.0",
    "tensorflow>=2.18.0",
    "toml>=0.10.2",
    "tqdm>=4.67.1",
]

[project.scripts]
suPAErnova = "suPAErnova:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# === Tools ===

[tool.basedpyright]
extends = "../../pyproject.toml"

[tool.ruff]
extend = "../../pyproject.toml"

[tool.ruff.lint]
logger-objects = [
    "suPAErnova.utils.logging",
]

