[project]
name = "supaernova"
version = "1.0.0"
description = "A Probabilistic Autoencoder for Type Ia Supernovae Spectral Time Series"
readme = "README.md"
requires-python = ">=3.12,<3.13"
license = { file = "LICENSE" }
authors = [
    { name = "Patrick Armstrong", email = "patrick.james.1998@gmail.com" },
]
dependencies = [
    "astropy",
    "cairocffi",
    "chainconsumer",
    "click",
    "coloredlogs",
    "matplotlib",
    "pandas",
    "pydantic",
    "sncosmo",
    "toml",
    "tqdm",
]

[project.optional-dependencies]
tf-cpu = [
    "tensorflow_cpu",
    "tf_keras",
    "tensorflow_probability",
    "tensorboard",
    "tensorboard_plugin_profile",
]

[dependency-groups]
dev = ["pandas_stubs", "types_tensorflow"]
docs = ["mkapi", "mkdocs_jupyter", "mkdocs_material", "mkdocs"]
jupyter = ["ipykernel", "jupyter"]
tests = ["pytest", "pytest_json_ctrf", "pytest_richer"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# === Tools ===
[tool.uv]
prerelease = "allow"
environments = ["sys_platform == 'linux'"]

# We override the tf_keras dependency metadata to avoid installing multiple version of tensorflow
[[tool.uv.dependency-metadata]]
name = "tf_keras"

[[tool.uv.dependency-metadata]]
name = "tf_keras_nightly"

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib", "--color=yes", "--tb=short"]
pythonpath = ["."]
testpaths = ["tests"]

[tool.ruff]
# Enumerate all fixed violations.
show-fixes = true
# Disable application of unsafe fixes.
unsafe-fixes = true

# --- Format: Ruff ---
[tool.ruff.format]
# Enable preview style formatting
preview = true
# Enable reformatting of code snippets in docstrings.
docstring-code-format = true

[tool.ruff.lint]
# Enable preview features
preview = true
# Show all lint rules (except preview) by default
select = ["ALL"]
# Rules to ignore
ignore = [
    "COM812",  # Missing trailing comma, already handled by formatter
    "E501",    # Line too long
    "ERA001",  # Found commented out code
    "G004",    # Logging statement uses f-string
    "N999",    # Invalid module name
    "PLR0913", # Too many arguments in function definition (_ > 5)
    "PLR0917", # Too many positional arguments (_/5)
    "ANN401",  # Allow *args: Any and **kwargs: Any
    "UP037",   # Don't remove quotes from type annotations
    "TC008",   # Don't remove quotes from type aliases
    "F722",    # Ignore forward annotation syntax errors
]
per-file-ignores = { "src/supaernova/configs/**.py" = [
    "TC001", # Move first party typing-only imports into a TYPE_CHECKING block. Breaks pydantic
    "TC002", # Move third party typing-only imports into a TYPE_CHECKING block. Breaks pydantic
    "TC003", # Move standard library typing-only imports into a TYPE_CHECKING block. Breaks pydantic
], "tests/**/*.py" = [
    "S101", # Don't warn when assert is used in tests
] }
# Consider all rules fixable
fixable = ["ALL"]
# Except these rules
unfixable = [
    "F401", # unused-import, will remove unused imports
    "F841", # unused-variable, will remove unused variables not prepended with an `_`
    "T201", # Print statements
]

# --- Flake8 ---
# Copyright Author
[tool.ruff.lint.flake8-copyright]
author = "Patrick Armstrong"

# Conventions for `from _ import _ as _`
[tool.ruff.lint.flake8-import-conventions.aliases]
matplotlib = "mpl"
"matplotlib.cm" = "cm"
"matplotlib.pyplot" = "plt"
numpy = "np"
pandas = "pd"
pytorch = "tch"
tensorflow = "tf"
keras = "ks"
tf_keras = "ks"
"tensorflow.keras" = "ks"
"tensorflow_probability" = "tfp"

# Type Checking
[tool.ruff.lint.flake8-type-checking]
# Move type-specific imports into an if statement
# By placing some type annotations in quotes
quote-annotations = true
# Be strict with type-specific imports
strict = true

# --- ISort ---
[tool.ruff.lint.isort]
case-sensitive = true
combine-as-imports = true
force-sort-within-sections = true
force-wrap-aliases = true
from-first = true
length-sort = true
length-sort-straight = true

# --- PyDocStyle ---
[tool.ruff.lint.pydocstyle]
convention = "google"
ignore-decorators = ["typing.overload"]
