[project]
name = "supaernova"
version = "1.0.0"
description = "A Probabilistic Autoencoder for Type Ia Supernovae Spectral Time Series"
readme = "README.md"
requires-python = ">=3.12,<3.13"
license = { file = "LICENSE" }
authors = [
    { name = "Patrick Armstrong", email = "patrick.james.1998@gmail.com" },
]
dependencies = [
    "astropy",
    "cairocffi",
    "chainconsumer",
    "click",
    "coloredlogs",
    "matplotlib<3.11",
    "pandas",
    "pydantic",
    "sncosmo",
    "toml",
    "tqdm",
    "tf_keras>=2.19,<2.20",
    "tensorboard>=2.19,<2.20",
    "tensorflow_probability>=0.25,<0.26",
    "numpy>2.1",
]

[project.optional-dependencies]
tf = ["tensorflow>=2.19,<2.20"]
tf-cpu = ["tensorflow_cpu>=2.19,<2.20"]
tf-rocm = ["tensorflow_rocm>=2.19,<2.20"]
tf-cuda = ["tensorflow[and-cuda]>=2.19,<2.20"]

[dependency-groups]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

# === Tools ===
[tool.uv]
environments = ["sys_platform == 'linux'"]
prerelease = "allow"
conflicts = [
    [
        { extra = "tf" },
        { extra = "tf-cpu" },
        { extra = "tf-rocm" },
        { extra = "tf-cuda" },
    ],
]

[tool.uv.sources]
tensorflow_rocm = [{ index = "rocm" }]

[[tool.uv.index]]
name = "rocm"
url = "https://repo.radeon.com/rocm/manylinux/rocm-rel-7.2.4/"
format = "flat"
explicit = true

[[tool.uv.dependency-metadata]]
name = "tf_keras"

[[tool.uv.dependency-metadata]]
name = "tf_keras_nightly"
