[project]
name = "suPAErnova"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Patrick Armstrong", email = "patrick.james.1998@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.8",
    "coloredlogs>=15.0.1",
    "pandas>=2.2.3",
    "tensorflow>=2.18.0",
    "toml>=0.10.2",
    "tqdm>=4.67.1",
]

[project.scripts]
suPAErnova = "suPAErnova:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# === Tools ===

# --- LSP: BasedPyRight ---
[tool.basedpyright]

# --- CMP: Ruff ---
[tool.ruff]

# --- Lint: Ruff ---
[tool.ruff.lint]

# --- Format: Ruff ---
[tool.ruff.format]
